name: matrix-demo
on: push
jobs:
  build:
    strategy:
      # idea behind matrix is that you can run your jobs with multiple configurations
      matrix:
        # bellow defined names are on us it can be anything except reserved words
        node-versions: [14, 12]
        operating-systems: [ubuntu-latest, windows-latest]
    # it will run same job(parallely) multiple times on different operating systems
    runs-on: ${{ matrix.operating-systems }}
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          # it will install different node versions on same job
          node-version: ${{ matrix.node-versions }}
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
